# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `banking`")
spark.sql("USE SCHEMA `bronze`")

# COMMAND ----------

display(spark.sql("SELECT * FROM samples.wanderbricks.users"))

# COMMAND ----------

df = spark.table("banking.silver.transactions")

# Check row count per region
df.groupBy("Region").count().orderBy("Region").show()

# COMMAND ----------

# Check individual bronze table counts
print("Enugu:",  spark.table("banking.bronze.enugu_transactions").count())
print("FCT:",    spark.table("banking.bronze.fct_transactions").count())
print("Kano:",   spark.table("banking.bronze.kano_transactions").count())
print("Lagos:",  spark.table("banking.bronze.lagos_transactions").count())

print("\nSilver total:", spark.table("banking.silver.transactions").count())

# COMMAND ----------

tables = [
    "transactions", "atm_locations", "customers",
    "calendar", "hour_lookup", "transaction_types"
]

for table in tables:
    try:
        count = spark.table(f"banking.silver.{table}").count()
        print(f"✅ banking.silver.{table:25s} → {count:,} rows")
    except:
        print(f"❌ banking.silver.{table:25s} → NOT FOUND")

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import DoubleType

# ── Helper: same cleaning logic as silver ────────────────────────────
def get_invalid_records(table_name):

    df = spark.table(f"banking.bronze.{table_name}")

    cols = [
        "TransactionID", "TransactionStartDateTime",
        "TransactionEndDateTime", "CardholderID",
        "LocationID", "TransactionTypeID",
        "TransactionAmount", "_source_file"
    ]
    df = df.select(cols)

    # Tag WHY each row is invalid
    df = df.withColumn("issue_null_TransactionID",
            F.when(F.col("TransactionID").isNull(), 1).otherwise(0)) \
           .withColumn("issue_null_CardholderID",
            F.when(F.col("CardholderID").isNull(), 1).otherwise(0)) \
           .withColumn("issue_null_LocationID",
            F.when(F.col("LocationID").isNull(), 1).otherwise(0)) \
           .withColumn("issue_null_TransactionTypeID",
            F.when(F.col("TransactionTypeID").isNull(), 1).otherwise(0)) \
           .withColumn("issue_null_Amount",
            F.when(F.col("TransactionAmount").isNull(), 1).otherwise(0)) \
           .withColumn("issue_zero_Amount",
            F.when(F.col("TransactionAmount") <= 0, 1).otherwise(0)) \
           .withColumn("issue_bad_StartDateTime",
            F.when(
                F.to_timestamp("TransactionStartDateTime", "M/d/yyyy H:mm").isNull(), 1
            ).otherwise(0)) \
           .withColumn("issue_bad_EndDateTime",
            F.when(
                F.to_timestamp("TransactionEndDateTime", "M/d/yyyy H:mm").isNull(), 1
            ).otherwise(0))

    # Keep only rows that have AT LEAST one issue
    invalid_df = df.filter(
        (F.col("issue_null_TransactionID")      == 1) |
        (F.col("issue_null_CardholderID")       == 1) |
        (F.col("issue_null_LocationID")         == 1) |
        (F.col("issue_null_TransactionTypeID")  == 1) |
        (F.col("issue_null_Amount")             == 1) |
        (F.col("issue_zero_Amount")             == 1) |
        (F.col("issue_bad_StartDateTime")       == 1) |
        (F.col("issue_bad_EndDateTime")         == 1)
    )

    return invalid_df

# ── Run for all 4 regional tables ────────────────────────────────────
tables = ["enugu_transactions", "fct_transactions",
          "kano_transactions",  "lagos_transactions"]

for table in tables:
    print(f"\n{'='*55}")
    print(f"🔍 INVALID RECORDS IN: {table.upper()}")
    print(f"{'='*55}")

    invalid = get_invalid_records(table)
    total_invalid = invalid.count()

    print(f"Total invalid rows: {total_invalid:,}")
    print("\nBreakdown by issue type:")

    issue_cols = [c for c in invalid.columns if c.startswith("issue_")]
    for issue in issue_cols:
        cnt = invalid.filter(F.col(issue) == 1).count()
        if cnt > 0:
            print(f"  ⚠️  {issue:40s} → {cnt:,} rows")

    print("\nSample of invalid records:")
    invalid.show(5, truncate=False)

# COMMAND ----------

gold_tables = [
    "transactions_enriched",
    "kpi_regional_summary",
    "kpi_customer_segments",
    "kpi_hourly_trends",
    "kpi_transaction_type_summary",
    "kpi_atm_performance"
]

for table in gold_tables:
    try:
        count = spark.table(f"banking.gold.{table}").count()
        print(f"✅ banking.gold.{table:35s} → {count:,} rows")
    except Exception as e:
        print(f"❌ banking.gold.{table:35s} → FAILED: {e}")

# COMMAND ----------


